### ISSUE TITLE
Adicionar linguagem natural ao bot

### ISSUE THREAD

**Issue by joaovitor3** [lappis-unb/alanaBot#6]
Após implementar comandos iniciais do bot, é necessário adicionar processamento de linguagem natural  ao bot para comandos utilizados pelo bot, por exemplo:
- /start: Breve introdução sobre as atividades que o bot realiza
- /ajuda: Ajuda sobre o que o bot realiza
- /ultimas: Comando que solicita o envio de mensagem sobre os últimos N projetos de lei. Exemplo: /ultimas 2, solicita o envio de mensagem dos últimos 2 projetos de lei
- /cadastro: Cadastra pessoas para receberem notificações de projetos de lei diariamente(de segunda a sexta)
- /descadastro: Descadastra pessoas de notificações de projetos de lei diariamente(de segunda a sexta)

Atividades:
- [x] Criar intenções com linguagem natural para comandos já existentes

- [x] Aprimorar Stories

- [x] Criar novas intents

- [x] Criar novas utters

- [x] Criação da personalidade da Alana

Critérios de aceitação:
- [x] Bot entender comandos também por linguagem natural

**Comment by RochaCarla** [comment]
@palomacmamede se tiver alguma dúvida em relaçao ao cotexto, procurar o Joao ou a mim

**Comment by palomacmamede** [comment]
**Proposta de personalidade da Alana**
[Proposta Alana.pdf](https://github.com/lappis-unb/alanaBot/files/3614157/Proposta.Alana.pdf)

**Comment by palomacmamede** [comment]
utter_cumprimentar:
    - text: |
        Oi, eu sou a Alana, a Assistente Virtual do programa Prioridade Absoluta.
        Estou aqui para te informar sobre as novidades das proposições de Leis para Crianças e Adolescentes.
        Afinal, cuidar das crianças e dos adolescentes, é cuidar de todos nós!

        Para conversar comigo basta escolher qual opção você prefere no momento:

        /cadastrar - Caso você deseje receber notificações sobre as novidades das Leis
        /descadastrar - Para deixar de receber as notificações
        /ajuda - Para entender como podemos interagir
        /ultimas - Para saber sobre as últimas novidades de Leis
        /sobrenos - Para conhecer um pouco mais sobre o nosso trabalho
        (você também pode me informar o número de tramitações que quer ver. Como neste exemplo: /ultimas 5).

        O que você deseja?

**Comment by palomacmamede** [comment]
utter_ajuda:
    - text: |
_Eu posso te enviar atualizações sobre as leis. Para isso posso te cadastrar, caso você escolha a opção /cadastrar 

Posso te /descadastrar, se você não quiser mais receber as minhas notificações.
E, posso te enviar as novidades que estão ocorrendo nas proposições de leis para Crianças e Adolescentes.
Todas que forem relevantes!

Posso também te falar um pouco do nosso trabalho na opção /sobrenos.
Você pode escolher o número de tramitações que deseja ver da seguinte forma: /ultimas 4.

Como posso te ajudar?
        /cadastrar
        /descadastrar
        /sobrenos
        /ultimas_

**Comment by palomacmamede** [comment]
**utter_despedir:
    - text: |**
Espero ter te ajudado a entender um pouco mais sobre as leis que podem ajudar as Crianças e Adolescentes.
Juntos podemos cuidar de quem precisa!
Até a próxima!

**Comment by palomacmamede** [comment]
**utter_sugestao:
    - text: |**
        Eu ainda estou em fase de testes e estou aprendendo com vocês, se você tem alguma sugestão de conteúdo me envia nesse email: contato@prioridadeabsoluta.org.br

**Comment by palomacmamede** [comment]
**utter_sobre_nos:
    - text: |**
    O Prioridade Absoluta é um programa do Instituto Alana criado com a missão de dar efetividade e visibilidade 
    ao Artigo 227 da Constituição Federal do Brasil, que estabelece os direitos e o melhor interesse de crianças 
    e adolescentes como absoluta prioridade das famílias, da sociedade e do Estado. 
    Para conhecer mais acesse o nosso siste: https://prioridadeabsoluta.org.br/.
    Se você deseja voltar para o menu digite: /voltarmenu
    Para me dar uma sugestão digite: /sugestao

**Comment by palomacmamede** [comment]
**utter_tudo_bem:
    - text: |**
        Estou bem, obrigada. Em que posso te ajudar?

        /cadastrar - Caso você deseje receber notificações sobre as novidades das Leis
        /descadastrar - Para deixar de receber as notificações
        /ajuda - Para entender como podemos interagir
        /ultimas - Para saber sobre as últimas novidades de Leis
        /sobrenos - Para conhecer um pouco mais sobre o nosso trabalho
        (você também pode me informar o número de tramitações que quer ver. Como neste exemplo: /ultimas 5).

**Comment by palomacmamede** [comment]
**utter_cumprimentar:
    - text: |**
Oi, eu sou a Alana, a Assistente Virtual do programa Prioridade Absoluta.
Estou aqui para te informar sobre as novidades das proposições de Leis para Crianças e Adolescentes. Afinal, cuidar das crianças e dos adolescentes, é cuidar de todos nós!
Para conversar comigo basta escolher qual opção você prefere no momento:
 /cadastrar - Caso você deseje receber notificações sobre as novidades das Leis
 /descadastrar - Para deixar de receber as notificações
 /ajuda - Para entender como podemos interagir
 /ultimas - Para saber sobre as últimas novidades de Leis
 /sobrenos - Para conhecer um pouco mais sobre o nosso trabalho
 /sugestao - Para me dizer uma sugestão
 (você também pode me informar o número de tramitações que quer ver. Como neste exemplo: /ultimas 5). O que você deseja?

  **utter_tudo_bem:
    - text: |**
Estou bem, obrigada. Em que posso te ajudar?
/cadastrar - Caso você deseje receber notificações sobre as novidades das Leis
/descadastrar - Para deixar de receber as notificações
/ajuda - Para entender como podemos interagir
/ultimas - Para saber sobre as últimas novidades de Leis
/sobrenos - Para conhecer um pouco mais sobre o nosso trabalho
/sugestao - Para me dizer uma sugestão
(você também pode me informar o número de tramitações que quer ver. Como neste exemplo: /ultimas 5).

  **utter_sugestao:
    - text: |**
        Eu ainda estou em fase de testes e estou aprendendo com vocês, se você tem alguma sugestão de conteúdo 
        me envia nesse email: contato@prioridadeabsoluta.org.br
        Se você deseja voltar ao menu digite: /voltarmenu

  **utter_ajuda:
    - text: |**
 Eu posso te enviar atualizações sobre as leis. Para isso posso te cadastrar, caso você escolha a opção /cadastrar.
Posso te /descadastrar, se você não quiser mais receber as minhas notificações.
E, posso te enviar as novidades que estão ocorrendo nas proposições de leis para Crianças e Adolescentes.
Todas que forem relevantes!
Você pode escolher o número de tramitações que deseja ver da seguinte forma: /ultimas 4.
Posso também te falar um pouco do nosso trabalho na opção /sobrenos.
Você pode me dizer uma sugestão escolhendo a opção /sugestao
Como posso te ajudar?
        /cadastrar
        /descadastrar
        /sobrenos
        /ultimas
        /sugestao

  **utter_sobre_nos:
    - text: |**
        O Prioridade Absoluta é um programa do Instituto Alana criado com a missão de dar efetividade e visibilidade ao Artigo 227 da Constituição Federal do Brasil, que estabelece os direitos e o melhor interesse de crianças e adolescentes como absoluta prioridade das famílias, da sociedade e do Estado. 
Para conhecer mais acesse o nosso siste: https://prioridadeabsoluta.org.br/.
Se você deseja voltar para o menu digite: /voltarmenu
Para me dar uma sugestão digite: /sugestao

  **utter_despedir:
    - text: |**
Espero ter te ajudado a entender um pouco mais sobre as leis que podem ajudar as Crianças e Adolescentes.
Juntos podemos cuidar de quem precisa!
Até a próxima!

**Comment by palomacmamede** [comment]
utter_cumprimentar:
    - text: |
        Oi, eu sou a Alana, a Assistente Virtual do programa Prioridade Absoluta.
        Estou aqui para te informar sobre as novidades das proposições de Leis para Crianças e Adolescentes.
        Afinal, cuidar das crianças e dos adolescentes, é cuidar de todos nós!
        Para conversar comigo basta escolher qual opção você prefere no momento:
        #cadastrar - Caso você deseje receber notificações sobre as novidades das Leis
        #descadastrar - Para deixar de receber as notificações
        #ajuda - Para entender como podemos interagir
        #ultimas - Para saber sobre as últimas novidades de Leis
        (você também pode me informar o número de tramitações que quer ver. Como neste exemplo: #ultimas 5)
        #sobrenos - Para conhecer um pouco mais sobre o nosso trabalho
        #sugestao - Para me dizer uma sugestão
        O que você deseja?

**Comment by palomacmamede** [comment]
utter_tudo_bem:
    - text: |
        Estou bem, obrigada. Em que posso te ajudar?
        #cadastrar - Caso você deseje receber notificações sobre as novidades das Leis
        #descadastrar - Para deixar de receber as notificações
        #ajuda - Para entender como podemos interagir
        #ultimas - Para saber sobre as últimas novidades de Leis
        (você também pode me informar o número de tramitações que quer ver. Como neste exemplo: #ultimas 5).
        #sobrenos - Para conhecer um pouco mais sobre o nosso trabalho
        #sugestao - Para me dizer uma sugestão

**Comment by palomacmamede** [comment]
utter_sugestao:
    - text: |
        Eu ainda estou em fase de testes e estou aprendendo com vocês, se você tem alguma sugestão de conteúdo 
        me envia nesse email: contato@prioridadeabsoluta.org.br
        Se você deseja voltar ao menu digite: #voltarmenu

**Comment by palomacmamede** [comment]
utter_ajuda:
    - text: |
        Eu posso te enviar atualizações sobre as leis. Para isso posso te cadastrar, caso você escolha a opção /cadastrar.
        Posso te /descadastrar, se você não quiser mais receber as minhas notificações.
        E, posso te enviar as novidades que estão ocorrendo nas proposições de leis para Crianças e Adolescentes.
        Todas que forem relevantes!
        Você pode escolher o número de tramitações que deseja ver da seguinte forma: #ultimas 4.
        Posso também te falar um pouco do nosso trabalho na opção /sobrenos.
        Você pode me dizer uma sugestão escolhendo a opção #sugestao
        Como posso te ajudar?
        #cadastrar
        #descadastrar
        #sobrenos
        #ultimas
        #sugestao

**Comment by palomacmamede** [comment]
utter_sobre_nos:
    - text: |
        O Prioridade Absoluta é um programa do Instituto Alana criado com a missão de dar efetividade e visibilidade 
        ao Artigo 227 da Constituição Federal do Brasil, que estabelece os direitos e o melhor interesse de crianças 
        e adolescentes como absoluta prioridade das famílias, da sociedade e do Estado. 
        Para conhecer mais acesse o nosso siste: https://prioridadeabsoluta.org.br/.
        Se você deseja voltar para o menu digite: #voltarmenu

**Comment by joaovitor3** [comment]
Issue fechada conforme comentado nesse [Pull Request](https://github.com/lappis-unb/alanaBot/pull/11)
