### ISSUE TITLE
Parceria com o coding Rights

### ISSUE THREAD

**Issue by RochaCarla** [lappis-unb/alanaBot#8]
Tivemos um hangouts com a Joana do Coding Rights, para ver a possibilidade de contribuir para o tramita bot utilizando o boilerplate.

Algumas necessidades foram levantadas:

- [x] Interação com linguagem natural (melhorar a experiência do usuário)

- [x] Usuário poder filtrar as PLs que querem seguir

- [x] Conexão com outros mensageiros (Twitter, facebook)

- [x]  Interesse nos dashboards - além do perfil de uso do bot, métricas e estatísticas sobre as PLs tramitadas no contexto 
 

- [x] Outro possível parceiro para consumo do bot: IBCCRIM

**Comment by joaovitor3** [comment]
Foi definido que parte da interação de diversas ongs iriam utilizar formulários do google para a adição de palavras chaves. Esses formulários estaríam vinculados à uma planilha do google que seria lida para retorno ao usuário via bot
